INSERT INTO "district" ("dist_name", "dist_photo") VALUES ('Dhaka', 'https://res.cloudinary.com/dvm1qpuvn/image/upload/v1749028831/Dhaka_ivxugd.jpg');
INSERT INTO "district" ("dist_name", "dist_photo") VALUES ('Rangpur', 'https://res.cloudinary.com/dvm1qpuvn/image/upload/v1749028938/Rangpur_ivvpfn.jpg');
INSERT INTO "district" ("dist_name", "dist_photo") VALUES ('Sylhet', 'https://res.cloudinary.com/dvm1qpuvn/image/upload/v1749029020/Sylhet_wxjxn7.jpg');
INSERT INTO "district" ("dist_name", "dist_photo") VALUES ('Patuakhali	', NULL);
INSERT INTO "sub_district" ("sub_dist_id", "dist_name", "sub_dist_name") VALUES ('1', 'Dhaka', 'Mirpur');
INSERT INTO "sub_district" ("sub_dist_id", "dist_name", "sub_dist_name") VALUES ('2', 'Dhaka', 'Mohammadpur');
INSERT INTO "sub_district" ("sub_dist_id", "dist_name", "sub_dist_name") VALUES ('3', 'Dhaka', 'Azimpur');
INSERT INTO "sub_district" ("sub_dist_id", "dist_name", "sub_dist_name") VALUES ('4', 'Rangpur', 'Pirgaccha');
INSERT INTO "sub_district" ("sub_dist_id", "dist_name", "sub_dist_name") VALUES ('6', 'Sylhet', 'Golapganj');
INSERT INTO "sub_district" ("sub_dist_id", "dist_name", "sub_dist_name") VALUES ('7', 'Dhaka', 'Banani');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('admin123', 'ADM', 'Yummy Admin', '123Admin', '111111111111111');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('ruhan-ruhan', 'CUS', 'Ruhan', '2205043R', '011111111111');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('shoyaib', 'CUS', 'Md. Shoyaib Rezwan', '2205014MSR', '01775899614');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('tokysami', 'CUS', 'Toky Tahmid Sami', '2205020TTS', '01755678109');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('hmahee', 'RID', 'Hasan Mahee', '2205015HFM', '01764245637');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('samimhb', 'RID', 'Sami Mahbub', '2205024SM', '01717713953');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('the-cuisine-hub', 'RES', 'The Cusine Hub', '1234567TCH', '99999999999');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('segreto', 'RES', 'Segreto', '1234567S', '99999999999');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('sugar-crush-and-co', 'RES', 'Sugar Crush And CO', '1234567SCAC', '99999999999');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('the-nest', 'RES', 'The Nest', '1234567TH', '99999999999');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('seasons-restaurant-and-cafe', 'RES', 'SEASONS Restaurant & Café', '1234567SRAC', '99999999999');
INSERT INTO "users" ("user_id", "user_type", "name", "password", "mobile") VALUES ('the-tehari-ghar-banani', 'RES', 'The Tehari Ghar Banai', '1234567TTGB', '99999999999');
INSERT INTO "admin" ("admin_id", "email", "commission_pct") VALUES ('admin123', 'admin@yummy.com', '0.1');
INSERT INTO "customer" ("customer_id", "email", "photo_url", "details", "sub_dist_id") VALUES ('ruhan-ruhan', 'ruhan123@gmail.com', 'http://res.cloudinary.com/dvm1qpuvn/image/upload/v1749129902/Customer_Photos/ymmbbcqyagvzm7emqeca.jpg', 'I am groot!!', '3');
INSERT INTO "customer" ("customer_id", "email", "photo_url", "details", "sub_dist_id") VALUES ('shoyaib', 'shoyaib@gmail.com', NULL, 'I like to eat rich foods', '1');
INSERT INTO "customer" ("customer_id", "email", "photo_url", "details", "sub_dist_id") VALUES ('tokysami', 'toky@gmail.com', NULL, 'I like all halal meat', NULL);
INSERT INTO "rider" ("rider_id", "curr_sub_dist", "email", "rider_details", "photo_url") VALUES ('hmahee', '1', 'mahee123@gmail.com', 'I like ac.', 'http://res.cloudinary.com/dvm1qpuvn/image/upload/v1749141128/Rider_Photos/jzapm36ktamf9ljqr1a2.jpg');
INSERT INTO "rider" ("rider_id", "curr_sub_dist", "email", "rider_details", "photo_url") VALUES ('samimhb', '1', 'samimahbub123@gmail.com', 'I like anime cosplay.', 'http://res.cloudinary.com/dvm1qpuvn/image/upload/v1749141358/Rider_Photos/ingeq1ejt0nl7jxfwx7l.jpg');
INSERT INTO "restaurant" ("rest_id", "sub_dist_id", "email", "opening_time", "closing_time", "close_until", "rest_details", "manager_name", "photo_url", "payment_method", "rating", "detailed_address") VALUES ('segreto', '1', NULL, '2000-01-01 10:00:00', '2000-01-01 20:00:00', NULL, NULL, 'Shoyaib', NULL, 'BOTH', '4.2', ' Shurma Bhaban, Plot No, 32 Rd No. 2, Mirpur 1216');
INSERT INTO "restaurant" ("rest_id", "sub_dist_id", "email", "opening_time", "closing_time", "close_until", "rest_details", "manager_name", "photo_url", "payment_method", "rating", "detailed_address") VALUES ('sugar-crush-and-co', '1', NULL, '2000-01-01 07:00:00', '2000-01-01 00:00:00', NULL, NULL, 'Shoyaib', NULL, 'BOTH', '4', ' Plot 14 & 15, Section 11, 01 Kalshi Rd, Mirpur');
INSERT INTO "restaurant" ("rest_id", "sub_dist_id", "email", "opening_time", "closing_time", "close_until", "rest_details", "manager_name", "photo_url", "payment_method", "rating", "detailed_address") VALUES ('the-nest', '2', NULL, '2000-01-01 18:00:00', '2000-01-01 00:00:00', NULL, NULL, 'Shoyaib', NULL, 'BOTH', '3.9', '1, 6 Nurjahan Rd, Dhaka 1207');
INSERT INTO "restaurant" ("rest_id", "sub_dist_id", "email", "opening_time", "closing_time", "close_until", "rest_details", "manager_name", "photo_url", "payment_method", "rating", "detailed_address") VALUES ('seasons-restaurant-and-cafe', '6', NULL, '2000-01-01 07:00:00', '2000-01-01 18:00:00', NULL, NULL, 'Shoyaib', NULL, 'BOTH', '4.2', 'Bihongo, 25/A Kazitula Rd, Sylhet 3100');
INSERT INTO "restaurant" ("rest_id", "sub_dist_id", "email", "opening_time", "closing_time", "close_until", "rest_details", "manager_name", "photo_url", "payment_method", "rating", "detailed_address") VALUES ('the-tehari-ghar-banani', '7', NULL, '2000-01-01 08:00:00', '2000-01-01 22:30:00', NULL, NULL, 'Toky', NULL, 'BOTH', '4.2', 'QCR4+JRM, Rd No 13, Dhaka 1212');
INSERT INTO "restaurant" ("rest_id", "sub_dist_id", "email", "opening_time", "closing_time", "close_until", "rest_details", "manager_name", "photo_url", "payment_method", "rating", "detailed_address") VALUES ('the-cuisine-hub', '1', NULL, '2000-01-01 08:00:00', '2000-01-01 21:00:00', NULL, NULL, 'Shoyaib', NULL, 'BOTH', '4.4', 'Top Floor, Ramjannessa Super Market, 142 Mirpur Senanibash Road, Dhaka 1216');
INSERT INTO "category" ("category_name") VALUES ('Fast Food');
INSERT INTO "category" ("category_name") VALUES ('Traditional');
INSERT INTO "category" ("category_name") VALUES ('Chicken');
INSERT INTO "category" ("category_name") VALUES ('Burger and Wraps');
INSERT INTO "category" ("category_name") VALUES ('Sandwiches');
INSERT INTO "category" ("category_name") VALUES ('Chinese');
INSERT INTO "category" ("category_name") VALUES ('Thai');
INSERT INTO "category" ("category_name") VALUES ('Italian');
INSERT INTO "category" ("category_name") VALUES ('Indian');
INSERT INTO "category" ("category_name") VALUES ('Mexican');
INSERT INTO "category" ("category_name") VALUES ('Continental');
INSERT INTO "category" ("category_name") VALUES ('Bangladeshi');
INSERT INTO "category" ("category_name") VALUES ('Seafood');
INSERT INTO "category" ("category_name") VALUES ('BBQ and Grills');
INSERT INTO "category" ("category_name") VALUES ('Sweets and Desserts');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('6', 'sugar-crush-and-co', 'Chocolate Lava Cake', 'Molten chocolate cake with vanilla ice cream.', '0.1', NULL, 't', '4.9');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('8', 'sugar-crush-and-co', 'Strawberry Cheesecake', 'Rich and creamy cheesecake with strawberry topping.', '0.2', NULL, 't', '4.7');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('9', 'sugar-crush-and-co', 'Red Velvet Cupcake', 'Moist red velvet cupcake with cream cheese frosting.', NULL, NULL, 't', '4.3');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('10', 'sugar-crush-and-co', 'Mini Macaron Box', 'Assorted French macarons in a gift box.', '0.1', NULL, 't', '4.5');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('11', 'the-nest', 'Grilled Chicken Sandwich', 'Toasted sandwich with grilled chicken and aioli.', '0.1', NULL, 't', '4.2');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('12', 'the-nest', 'Nest Special Breakfast', 'Eggs, toast, sausages, and hash browns.', NULL, NULL, 't', '4.1');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('14', 'the-nest', 'Veggie Wrap', 'Wrap filled with fresh grilled vegetables and hummus.', '0.05', NULL, 't', '4.0');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('15', 'the-nest', 'Cheesy Omelette', 'Omelette with cheese, herbs, and bell peppers.', '0.1', NULL, 't', '4.4');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('16', 'seasons-restaurant-and-cafe', 'Seasonal Fruit Salad', 'Fresh fruits with mint and honey dressing.', '0.1', NULL, 't', '4.0');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('18', 'seasons-restaurant-and-cafe', 'Cream of Mushroom Soup', 'Warm mushroom soup with cream and garlic.', NULL, NULL, 't', '4.2');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('19', 'seasons-restaurant-and-cafe', 'Club Sandwich', 'Triple layered sandwich with chicken and veggies.', '0.05', NULL, 't', '4.3');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('20', 'seasons-restaurant-and-cafe', 'Iced Lemon Tea', 'Cold lemon tea served with mint.', '0.1', NULL, 't', '4.1');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('22', 'the-tehari-ghar-banani', 'Chicken Tehari', 'Spicy chicken tehari with aromatic rice.', '0.05', NULL, 't', '4.5');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('23', 'the-tehari-ghar-banani', 'Egg Tehari', 'Tehari served with boiled egg and salad.', '0.1', NULL, 't', '4.3');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('24', 'the-tehari-ghar-banani', 'Beef Shami Kebab', 'Fried beef patties served with tehari.', '0.15', NULL, 't', '4.4');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('26', 'the-cuisine-hub', 'Fried Rice with Chicken', 'Stir-fried rice with chicken, vegetables and soy.', '0.1', NULL, 't', '4.5');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('27', 'the-cuisine-hub', 'Chicken Manchurian', 'Spicy Indo-Chinese chicken in red sauce.', '0.05', NULL, 't', '4.3');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('28', 'the-cuisine-hub', 'Sweet and Sour Prawns', 'Prawns in sweet and tangy sauce.', '0.1', NULL, 't', '4.6');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('30', 'the-cuisine-hub', 'Fuchka Platter', 'Crispy fuchka with spiced tamarind filling.', NULL, NULL, 't', '4.7');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('1', 'segreto', 'Chicken Alfredo Pasta', 'Creamy Alfredo pasta with grilled chicken and herbs.', '0.1', '', 't', '4.5');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('2', 'segreto', 'Classic Margherita Pizza', 'Stone-baked pizza with tomato, mozzarella, and basil.', '0.15', '', 't', '4.7');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('4', 'segreto', 'Garlic Breadsticks', 'Toasted breadsticks with garlic butter and herbs.', '0.05', NULL, 'f', '4.2');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('5', 'segreto', 'Mushroom Risotto', 'Creamy risotto with sautéed mushrooms and parmesan.', NULL, NULL, 'f', '4.6');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('7', 'sugar-crush-and-co', 'Rainbow Donuts', 'Colorful donuts with fruity glaze and sprinkles.', '0.05', NULL, 'f', '4.4');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('13', 'the-nest', 'Cold Coffee', 'Chilled coffee with milk and ice cream.', '0.15', NULL, 'f', '4.3');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('17', 'seasons-restaurant-and-cafe', 'Beef Steak', 'Grilled beef steak with mashed potatoes.', '0.15', NULL, 'f', '4.6');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('21', 'the-tehari-ghar-banani', 'Beef Tehari', 'Authentic Dhakaiya beef tehari with fragrant rice.', '0.1', NULL, 'f', '4.8');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('25', 'the-tehari-ghar-banani', 'Borhani', 'Spiced yogurt drink served with meals.', NULL, NULL, 'f', '4.6');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('29', 'the-cuisine-hub', 'Vegetable Chow Mein', 'Stir-fried noodles with assorted vegetables.', '0.05', NULL, 'f', '4.2');
INSERT INTO "dish" ("dish_id", "rest_id", "dish_name", "dish_details", "discount", "photo_url", "available", "rating") VALUES ('3', 'segreto', 'Tiramisu', 'Traditional Italian layered dessert with mascarpone.', '0.2', '', 'f', '4.8');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('1', 'Italian');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('1', 'Chicken');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('2', 'Italian');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('2', 'Burger and Wraps');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('3', 'Italian');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('3', 'Sweets and Desserts');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('4', 'Fast Food');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('4', 'Continental');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('5', 'Continental');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('5', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('6', 'Sweets and Desserts');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('7', 'Sweets and Desserts');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('8', 'Sweets and Desserts');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('9', 'Sweets and Desserts');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('10', 'Sweets and Desserts');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('11', 'Chicken');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('11', 'Sandwiches');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('12', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('12', 'Fast Food');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('13', 'Fast Food');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('14', 'Burger and Wraps');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('14', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('15', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('16', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('16', 'Continental');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('17', 'BBQ and Grills');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('17', 'Continental');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('18', 'Continental');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('18', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('19', 'Sandwiches');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('19', 'Fast Food');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('20', 'Fast Food');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('21', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('21', 'Bangladeshi');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('22', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('22', 'Chicken');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('23', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('24', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('24', 'Bangladeshi');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('25', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('26', 'Chinese');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('26', 'Chicken');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('27', 'Chinese');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('27', 'Chicken');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('28', 'Chinese');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('28', 'Seafood');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('29', 'Chinese');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('29', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('30', 'Traditional');
INSERT INTO "dish_category_linker" ("dish_id", "category_name") VALUES ('30', 'Fast Food');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('93', 'Regular Portion', '1', '450');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('94', 'Large Portion', '1', '550');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('95', 'Extra Chicken', '1', '500');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('96', 'Truffle Upgrade', '1', '600');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('97', 'Classic 10"', '2', '500');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('98', 'Family 14"', '2', '700');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('99', 'Extra Cheese', '2', '550');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('100', 'Gluten-Free Crust', '2', '600');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('101', 'Single Slice', '3', '250');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('102', 'Double Portion', '3', '450');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('103', 'With Coffee Pairing', '3', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('104', '6-Piece', '4', '180');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('105', '12-Piece', '4', '300');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('106', 'Cheese Stuffed', '4', '250');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('107', 'Lunch Portion', '5', '400');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('108', 'Dinner Portion', '5', '500');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('109', 'Truffle Oil Upgrade', '5', '550');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('110', 'Standard', '6', '300');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('111', 'With Ice Cream', '6', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('112', 'Double Chocolate', '6', '320');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('113', 'Single Donut', '7', '120');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('114', 'Half Dozen', '7', '650');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('115', 'Special Glaze', '7', '150');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('116', 'Classic Slice', '8', '300');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('117', 'Whole Cake (8")', '8', '1400');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('118', 'With Fresh Berries', '8', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('119', 'Single', '9', '150');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('120', 'Half Dozen', '9', '800');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('121', 'Special Occasion Decor', '9', '200');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('122', '6-Piece', '10', '450');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('123', '12-Piece', '10', '800');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('124', 'Custom Flavor Set', '10', '550');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('125', 'Classic', '11', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('126', 'Combo with Fries', '11', '450');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('127', 'Spicy Version', '11', '380');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('128', 'Standard', '12', '400');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('129', 'Vegetarian Option', '12', '380');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('130', 'Extra Large', '12', '500');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('131', 'Regular', '13', '150');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('132', 'Large', '13', '180');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('133', 'With Whipped Cream', '13', '200');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('134', 'Standard', '14', '300');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('135', 'With Avocado', '14', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('136', 'Gluten-Free Wrap', '14', '320');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('137', '3-Egg', '15', '280');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('138', '5-Egg', '15', '380');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('139', 'Premium Cheese Blend', '15', '320');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('140', 'Small', '16', '250');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('141', 'Large', '16', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('142', 'With Yogurt', '16', '300');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('143', '8oz', '17', '800');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('144', '12oz', '17', '1000');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('145', 'With Red Wine Sauce', '17', '900');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('146', 'Cup', '18', '200');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('147', 'Bowl', '18', '300');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('148', 'Truffle Infused', '18', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('149', 'Classic', '19', '400');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('150', 'Double Decker', '19', '450');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('151', 'With Sweet Potato Fries', '19', '500');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('152', 'Regular', '20', '150');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('153', 'Large', '20', '180');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('154', 'With Mint & Honey', '20', '160');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('155', 'Regular', '22', '300');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('156', 'Special Spicy', '22', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('157', 'Family Pack', '22', '550');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('158', 'Standard', '23', '280');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('159', 'Extra Egg', '23', '320');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('160', 'With Borhani', '23', '380');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('161', '4-Piece', '24', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('162', '8-Piece', '24', '600');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('163', 'Combo with Tehari', '24', '450');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('164', 'Regular', '21', '400');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('165', 'Special', '21', '450');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('166', 'With Salad & Borhani', '21', '500');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('167', 'Small', '25', '100');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('168', 'Large', '25', '180');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('169', 'Special Masala', '25', '150');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('170', 'Lunch Portion', '26', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('171', 'Dinner Portion', '26', '450');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('172', 'Extra Chicken', '26', '400');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('173', 'Standard', '27', '380');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('174', 'Extra Spicy', '27', '400');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('175', 'Combo with Rice', '27', '450');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('176', '8-Piece', '28', '550');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('177', '12-Piece', '28', '750');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('178', 'With Fried Rice', '28', '600');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('179', 'Regular', '29', '300');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('180', 'Large', '29', '400');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('181', 'With Extra Vegetables', '29', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('182', '6-Piece', '30', '200');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('183', '12-Piece', '30', '350');
INSERT INTO "dish_sub_category" ("sub_cat_id", "sub_cat_name", "dish_id", "price") VALUES ('184', 'Special Tangy', '30', '250');
INSERT INTO "cart" ("cart_id", "customer_id", "create_time", "rest_id", "cart_status") VALUES ('16', 'shoyaib', '2025-07-05 08:05:59.8159', 'sugar-crush-and-co', 'COMPLETED');
INSERT INTO "cart" ("cart_id", "customer_id", "create_time", "rest_id", "cart_status") VALUES ('18', 'shoyaib', '2025-07-05 11:21:00.039933', 'sugar-crush-and-co', 'COMPLETED');
INSERT INTO "cart" ("cart_id", "customer_id", "create_time", "rest_id", "cart_status") VALUES ('19', 'shoyaib', '2025-07-05 11:23:14.974346', 'sugar-crush-and-co', 'COMPLETED');
INSERT INTO "cart" ("cart_id", "customer_id", "create_time", "rest_id", "cart_status") VALUES ('20', 'shoyaib', '2025-07-05 11:29:43.037914', 'sugar-crush-and-co', 'COMPLETED');
INSERT INTO "cart" ("cart_id", "customer_id", "create_time", "rest_id", "cart_status") VALUES ('21', 'shoyaib', '2025-07-05 12:43:51.473147', 'the-cuisine-hub', 'COMPLETED');
INSERT INTO "cart_item" ("sub_cat_id", "cart_id", "quantity", "order_specification") VALUES ('116', '16', '2', NULL);
INSERT INTO "cart_item" ("sub_cat_id", "cart_id", "quantity", "order_specification") VALUES ('122', '16', '2', NULL);
INSERT INTO "cart_item" ("sub_cat_id", "cart_id", "quantity", "order_specification") VALUES ('124', '16', '2', NULL);
INSERT INTO "cart_item" ("sub_cat_id", "cart_id", "quantity", "order_specification") VALUES ('110', '16', '2', NULL);
INSERT INTO "cart_item" ("sub_cat_id", "cart_id", "quantity", "order_specification") VALUES ('110', '18', '3', NULL);
INSERT INTO "cart_item" ("sub_cat_id", "cart_id", "quantity", "order_specification") VALUES ('110', '19', '2', NULL);
INSERT INTO "cart_item" ("sub_cat_id", "cart_id", "quantity", "order_specification") VALUES ('120', '20', '1', NULL);
INSERT INTO "cart_item" ("sub_cat_id", "cart_id", "quantity", "order_specification") VALUES ('182', '21', '2', NULL);
INSERT INTO "cart_item" ("sub_cat_id", "cart_id", "quantity", "order_specification") VALUES ('176', '21', '1', NULL);
