CREATE TABLE DISTRICT(
  DIST_NAME VARCHAR2(100) CONSTRAINT DISTRICT_PK PRIMARY KEY,
  DIST_PHOTO VARCHAR2(2000)
);

CREATE SEQUENCE SUB_DIST_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;


CREATE TABLE SUB_DISTRICT(
  SUB_DIST_ID NUMBER DEFAULT SUB_DIST_ID_SEQ.NEXTVAL CONSTRAINT SUB_DISTRICT_PK PRIMARY KEY,
  DIST_NAME VARCHAR2(100) NOT NULL,
  SUB_DIST_NAME VARCHAR2(100) NOT NULL,
  CONSTRAINT SUB_DISTRICT_FK1 FOREIGN KEY (DIST_NAME) REFERENCES DISTRICT(DIST_NAME)
) ;


CREATE TABLE USERS(
  USER_ID VARCHAR2(30) CONSTRAINT USER_PK PRIMARY KEY CHECK (REGEXP_LIKE(USER_ID, '^[a-z][a-z0-9._-]{4,29}$')),
  USER_TYPE VARCHAR2(5) NOT NULL CHECK(USER_TYPE IN ('ADM','RES','CUS','RID')),
  NAME VARCHAR2(100) NOT NULL,
  PASSWORD VARCHAR2(50) NOT NULL CHECK (
  REGEXP_LIKE(PASSWORD, '^(?=.*[A-Za-z])(?=.*\d).{8,50}$')),
  MOBILE VARCHAR2(15) NOT NULL
);

CREATE TABLE ADMIN(
  ADMIN_ID VARCHAR2(30) CONSTRAINT ADMIN_PK PRIMARY KEY,
  EMAIL VARCHAR2(254) NOT NULL CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
  ),
  COMMISSION_PCT NUMBER CHECK(COMMISSION_PCT>0 AND COMMISSION_PCT<0.5),
  CONSTRAINT ADMIN_FK1 FOREIGN KEY (ADMIN_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE CUSTOMER(
  CUSTOMER_ID VARCHAR2(30) CONSTRAINT CUSTOMER_PK PRIMARY KEY,
  EMAIL VARCHAR2(254) CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
  ),
  PHOTO_URL VARCHAR2(2000),
  DETAILS VARCHAR2(4000),
  SUB_DIST_ID NUMBER,
  CONSTRAINT CUSTOMER_FK1 FOREIGN KEY (CUSTOMER_ID) REFERENCES USERS(USER_ID)
  ON DELETE CASCADE,
  CONSTRAINT CUSTOMER_FK2 FOREIGN KEY (SUB_DIST_ID) REFERENCES SUB_DISTRICT(SUB_DIST_ID)
  ON DELETE SET NULL
);

CREATE TABLE RESTAURANT(
  REST_ID VARCHAR2(30) CONSTRAINT RESTAURANT_PK PRIMARY KEY,
  SUB_DIST_ID NUMBER NOT NULL,
  EMAIL VARCHAR2(254) CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
  ),
  OPENING_TIME DATE NOT NULL,
  CLOSING_TIME DATE NOT NULL,
  CLOSE_UNTIL DATE,
  REST_DETAILS VARCHAR2(4000),
  MANAGER_NAME VARCHAR2(100) NOT NULL,
  PHOTO_URL VARCHAR2(2000),
  PAYMENT_METHOD VARCHAR2(10) NOT NULL CHECK(PAYMENT_METHOD IN ('COD', 'ONLINE', 'BOTH')),
  RATING NUMBER CHECK(RATING >=0 AND RATING <=5),
  ACCEPTED CHAR(1) NOT NULL  CHECK (ACCEPTED IN ('Y','N')),
  CONSTRAINT RESTAURANT_FK1 FOREIGN KEY (REST_ID) REFERENCES USERS(USER_ID),
  CONSTRAINT RESTAURANT_FK2 FOREIGN KEY (SUB_DIST_ID) REFERENCES SUB_DISTRICT(SUB_DIST_ID)
);

CREATE TABLE CATEGORY(
  CATEGORY_NAME VARCHAR2(50) CONSTRAINT CATEGORY_PK PRIMARY KEY
);

CREATE SEQUENCE DISH_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;

CREATE TABLE DISH(
  DISH_ID NUMBER DEFAULT DISH_ID_SEQ.NEXTVAL CONSTRAINT DISH_PK PRIMARY KEY,
  REST_ID VARCHAR2(30) NOT NULL,
  DISH_NAME VARCHAR2(100) NOT NULL,
  DISH_DETAILS VARCHAR2(4000) NOT NULL,
  DISCOUNT NUMBER CHECK(DISCOUNT>=0 AND DISCOUNT<=1),
  AVAILABLE_AMOUNT NUMBER NOT NULL CHECK (AVAILABLE_AMOUNT>=0 AND MOD(AVAILABLE_AMOUNT,1)=0),
  PHOTO_URL VARCHAR2(2000),
  RATING NUMBER CHECK(RATING >=0 AND RATING <=5),
  CONSTRAINT DISH_FK1 FOREIGN KEY (REST_ID) REFERENCES RESTAURANT(REST_ID)
  ON DELETE CASCADE
);

CREATE TABLE DISH_CATEGORY_LINKER(
  DISH_ID NUMBER,
  CATEGORY_NAME VARCHAR2(50),
  CONSTRAINT DISH_CATEGORY_LINKER_PK PRIMARY KEY (DISH_ID, CATEGORY_NAME),
  CONSTRAINT DISH_CATEGORY_LINKER_FK1 FOREIGN KEY (DISH_ID) REFERENCES DISH(DISH_ID)
  ON DELETE CASCADE,
  CONSTRAINT DISH_CATEGORY_LINKER_FK2 FOREIGN KEY (CATEGORY_NAME) REFERENCES CATEGORY(CATEGORY_NAME)
  ON DELETE CASCADE
);

CREATE TABLE RIDER(
  RIDER_ID VARCHAR2(30) CONSTRAINT RIDER_PK PRIMARY KEY,
  CURR_SUB_DIST NUMBER NOT NULL,
  EMAIL VARCHAR2(254) CHECK (REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
  ),
  RIDER_DETAILS VARCHAR2(4000),
  CONSTRAINT RIDER_FK1 FOREIGN KEY (RIDER_ID) REFERENCES USERS(USER_ID)
  ON DELETE CASCADE
);

CREATE SEQUENCE SUB_CAT_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;

CREATE TABLE DISH_SUB_CATEGORY(
  SUB_CAT_ID NUMBER DEFAULT SUB_CAT_ID_SEQ.NEXTVAL CONSTRAINT DISH_SUB_CATEGORY_PK PRIMARY KEY,
  SUB_CAT_NAME VARCHAR2(50) NOT NULL,
  DISH_ID NUMBER NOT NULL,
  PRICE NUMBER NOT NULL CHECK (PRICE >=0),
  CONSTRAINT DISH_SUB_CATEGORY_FK1 FOREIGN KEY (DISH_ID) REFERENCES DISH(DISH_ID)
  ON DELETE CASCADE
);

CREATE SEQUENCE CART_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;

CREATE TABLE CART(
  CART_ID NUMBER DEFAULT CART_ID_SEQ.NEXTVAL CONSTRAINT CART_PK PRIMARY KEY,
  CUSTOMER_ID VARCHAR2(30),
  CREATE_TIME DATE DEFAULT SYSDATE,
  CART_STATUS VARCHAR2(10) NOT NULL CHECK( CART_STATUS IN ('ACTIVE', 'COMPLETED')),
  CONSTRAINT CART_PK1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
  ON DELETE SET NULL
);

CREATE TABLE CART_ITEM(
  SUB_CAT_ID NUMBER NOT NULL,
  CART_ID NUMBER NOT NULL, 
  QUANTITY NUMBER NOT NULL CHECK(QUANTITY>0 AND MOD(QUANTITY,1)=0),
  ORDER_SPECIFICATION VARCHAR2 (500),
  CONSTRAINT CART_ITEM_PK PRIMARY KEY (SUB_CAT_ID,CART_ID),
  CONSTRAINT CART_ITEM_FK1 FOREIGN KEY (SUB_CAT_ID) REFERENCES DISH_SUB_CATEGORY(SUB_CAT_ID)
  ON DELETE CASCADE,
  CONSTRAINT CART_ITEM_FK2 FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID)
  ON DELETE CASCADE
);

CREATE TABLE ORDER_(
  ORDER_ID NUMBER CONSTRAINT ORDER_PK PRIMARY KEY,
  DELIVERY_METHOD VARCHAR2(20) NOT NULL CHECK (DELIVERY_METHOD IN('PICKUP', 'HOME-DELIVERY')),
  ORDER_STATUS VARCHAR2(25) NOT NULL CHECK (ORDER_STATUS IN('PENDING', 'RESTAURANT_RECEIVED','RIDER_PICKED', 'CUSTOMER_RECEIVED','ORDER_CANCELED')), 
  SUB_DIST_ID NUMBER,
  PROPOSED_DELIVERY_TIME DATE,
  DETAILED_ADDRESS VARCHAR2(500),
  CONSTRAINT ORDER_FK1 FOREIGN KEY (ORDER_ID ) REFERENCES CART(CART_ID )
  ON DELETE CASCADE,
  CONSTRAINT ORDER_FK2 FOREIGN KEY (SUB_DIST_ID ) REFERENCES SUB_DISTRICT(SUB_DIST_ID )
  ON DELETE SET NULL
);

CREATE SEQUENCE DELIVERY_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;
  
CREATE TABLE DELIVERY(
  DELIVERY_ID NUMBER DEFAULT DELIVERY_ID_SEQ.NEXTVAL CONSTRAINT DELIVERY_PK PRIMARY KEY,
  ORDER_ID NUMBER,
  RIDER_ID VARCHAR2(30) NOT NULL,
  DELIVERY_CHARGE NUMBER NOT NULL CHECK (DELIVERY_CHARGE>=0),
  DELIVERY_STATUS VARCHAR2(15) NOT NULL CHECK(DELIVERY_STATUS IN ('ON_DELIVERY', 'DELIVERED')),
  CONSTRAINT DELIVERY_FK1 FOREIGN KEY (ORDER_ID ) REFERENCES ORDER_(ORDER_ID)
  ON DELETE SET NULL,
  CONSTRAINT DELIVERY_FK2 FOREIGN KEY (RIDER_ID) REFERENCES RIDER(RIDER_ID)
  ON DELETE CASCADE
);

CREATE SEQUENCE PAYMENT_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;


CREATE TABLE PAYMENT (
  PAYMENT_ID NUMBER DEFAULT PAYMENT_ID_SEQ.NEXTVAL CONSTRAINT PAYMENT_PK PRIMARY KEY,
  ORDER_ID NUMBER,
  PAYMENT_METHOD VARCHAR2(10) NOT NULL CHECK (PAYMENT_METHOD IN ('COD', 'ONLINE')),
  PAYMENT_STATUS VARCHAR2(20) NOT NULL CHECK (PAYMENT_STATUS IN ('NOT PAID', 'PARTIALLY_PAID', 'RIDER_PAID', 'RESTAURANT_PAID')),
  PAYMENT_AMOUNT NUMBER NOT NULL CHECK (PAYMENT_AMOUNT >= 0),

  CONSTRAINT PAYMENT_FK1 FOREIGN KEY (ORDER_ID) REFERENCES ORDER_(ORDER_ID)
  ON DELETE SET NULL
);

CREATE SEQUENCE COUPON_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;


CREATE TABLE COUPON(
  COUPON_ID NUMBER DEFAULT COUPON_ID_SEQ.NEXTVAL CONSTRAINT COUPON_PK PRIMARY KEY,
  COUPON_TYPE VARCHAR2(20) NOT NULL CHECK (COUPON_TYPE IN('UNIVERSAL', 'RESTAURANT')),
  REST_ID VARCHAR2(30),
  DESCRIPTION VARCHAR2(500) NOT NULL,
  DISCOUNT_TYPE VARCHAR2(20) NOT NULL CHECK(DISCOUNT_TYPE IN('FLAT', 'PERCENT')),
  DISCOUNT NUMBER NOT NULL CHECK(DISCOUNT>0),
  UPPER_LIMIT NUMBER NOT NULL,
  START_TIME DATE DEFAULT SYSDATE NOT NULL,
  END_TIME DATE NOT NULL,
  USAGE_LIMIT NUMBER NOT NULL,
  PER_USER_USE_LIMIT NUMBER NOT NULL,
  PRICE NUMBER NOT NULL CHECK(PRICE>=0),
  CONSTRAINT COUPON_FK1 FOREIGN KEY (REST_ID) REFERENCES RESTAURANT(REST_ID) 
  ON DELETE CASCADE,
  CONSTRAINT COUPON_REST_ID_REQUIRED CHECK (
    (COUPON_TYPE = 'RESTAURANT' AND REST_ID IS NOT NULL) OR
    (COUPON_TYPE = 'UNIVERSAL' AND REST_ID IS NULL)
  )
);

CREATE TABLE CUSTOMER_COUPON(
  COUPON_ID NUMBER NOT NULL,
  CUSTOMER_ID VARCHAR2(30) NOT NULL,
  USE_COUNT NUMBER NOT NULL CHECK(USE_COUNT>=0 AND MOD(USE_COUNT,1)=0),
  CONSTRAINT CUSTOMER_COUPON_PK PRIMARY KEY (COUPON_ID,CUSTOMER_ID),
  CONSTRAINT CUSTOMER_COUPON_FK1 FOREIGN KEY (COUPON_ID) REFERENCES COUPON(COUPON_ID)
  ON DELETE CASCADE,
  CONSTRAINT CUSTOMER_COUPON_FK2 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
  ON DELETE CASCADE
);

CREATE SEQUENCE REVIEW_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;

CREATE TABLE REVIEW (
  REVIEW_ID NUMBER DEFAULT REVIEW_ID_SEQ.NEXTVAL CONSTRAINT REVIEW_PK PRIMARY KEY,
  CUSTOMER_ID VARCHAR2(30) NOT NULL,
  REVIEW_TYPE VARCHAR2(15) NOT NULL CHECK(REVIEW_TYPE IN('SYSTEM', 'RESTAURANT', 'DISH')),
  REST_ID VARCHAR2(30),
  DISH_ID NUMBER,
  REVIEW_TEXT VARCHAR2(1000),
  RATING NUMBER NOT NULL CHECK(RATING>=0 AND RATING<=5),
  REVIEW_TIME DATE DEFAULT SYSDATE,
  CONSTRAINT REVIEW_FK1 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
  ON DELETE CASCADE,
  CONSTRAINT REVIEW_FK2 FOREIGN KEY (REST_ID) REFERENCES RESTAURANT(REST_ID)
  ON DELETE CASCADE,
  CONSTRAINT REVIEW_FK3 FOREIGN KEY (DISH_ID) REFERENCES DISH(DISH_ID)
  ON DELETE CASCADE,
  CONSTRAINT REVIEW_CONSTRAINTS CHECK(
    (REVIEW_TYPE= 'SYSTEM' AND REST_ID IS NULL AND DISH_ID IS NULL) OR
    (REVIEW_TYPE= 'RESTAURANT' AND REST_ID IS NOT NULL AND DISH_ID IS NULL) OR
    (REVIEW_TYPE= 'DISH' AND DISH_ID IS NOT NULL) 
  )
);


CREATE SEQUENCE WALLET_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;

CREATE TABLE WALLET(
  WALLET_ID NUMBER DEFAULT WALLET_ID_SEQ.NEXTVAL CONSTRAINT WALLET_PK PRIMARY KEY,
  USER_ID VARCHAR2(30) NOT NULL,
  BALANCE NUMBER NOT NULL CHECK(BALANCE>=0),
  CONSTRAINT WALLET_FK1 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
  ON DELETE CASCADE
);

CREATE TABLE CARD(
  CARD_NO VARCHAR2(20) CONSTRAINT CARD_NO_VALID CHECK (REGEXP_LIKE(CARD_NO, '^\d{16}$')) CONSTRAINT CARD_PK PRIMARY KEY,
  WALLET_ID NUMBER NOT NULL,
  EXPIRY_DATE DATE NOT NULL,
  CARD_HOLDER_NAME VARCHAR2(50) NOT NULL,
  CARD_TYPE VARCHAR2(20) NOT NULL CHECK( CARD_TYPE IN ('VISA', 'MASTERCARD', 'OTHER')),
  CONSTRAINT CARD_FK1 FOREIGN KEY (WALLET_ID) REFERENCES WALLET(WALLET_ID)
  ON DELETE CASCADE
);

CREATE SEQUENCE MESSAGE_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;

CREATE TABLE MESSAGE(
  MESSAGE_ID NUMBER DEFAULT MESSAGE_ID_SEQ.NEXTVAL CONSTRAINT MESSAGE_PK PRIMARY KEY,
  SENDER_ID VARCHAR2(30) NOT NULL,
  RECIPIENT_ID VARCHAR2(30) NOT NULL,
  MSG_TIME DATE DEFAULT SYSDATE,
  MESSAGE_TEXT VARCHAR2(1000) NOT NULL,
  CONSTRAINT MESSAGE_FK1 FOREIGN KEY(SENDER_ID) REFERENCES USERS(USER_ID)
  ON DELETE CASCADE,
  CONSTRAINT MESSAGE_FK2 FOREIGN KEY(RECIPIENT_ID) REFERENCES USERS(USER_ID)
  ON DELETE CASCADE
);

CREATE SEQUENCE COMPLAINT_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;


CREATE TABLE COMPLAINT(
  COMPLAINT_ID NUMBER DEFAULT COMPLAINT_ID_SEQ.NEXTVAL CONSTRAINT COMPLAINT_PK PRIMARY KEY,
  COMPLAINER_ID VARCHAR2(30) NOT NULL,
  ACCUSED_ID VARCHAR2(30) NOT NULL,
  COMPLAIN_TIME DATE DEFAULT SYSDATE,
  COMPLAIN_TEXT VARCHAR2(1000) NOT NULL,
  CONSTRAINT COMPLAINT_FK1 FOREIGN KEY(COMPLAINER_ID) REFERENCES USERS(USER_ID)
  ON DELETE CASCADE,
  CONSTRAINT COMPLAINT_FK2 FOREIGN KEY(ACCUSED_ID) REFERENCES USERS(USER_ID)
  ON DELETE CASCADE
);

CREATE SEQUENCE PENALTY_ID_SEQ
START WITH 1
MAXVALUE 1000000000
NOCYCLE;

CREATE TABLE PENALTY(
  PENALTY_ID NUMBER DEFAULT PENALTY_ID_SEQ.NEXTVAL CONSTRAINT PENALTY_PK PRIMARY KEY,
  DESCRIPTION VARCHAR2(4000) NOT NULL,
  FINE NUMBER,
  PENALTY_DEADLINE DATE
);

CREATE TABLE COMPLAINT_PENALTY_LINKER(
  COMPLAINT_ID NUMBER NOT NULL,
  PENALTY_ID NUMBER NOT NULL,
  CONSTRAINT COMPLAINT_PENALTY_LINKER_PK PRIMARY KEY (COMPLAINT_ID,PENALTY_ID),
  CONSTRAINT COMPLAINT_PENALTY_LINKER_FK1 FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINT(COMPLAINT_ID)
  ON DELETE CASCADE,
  CONSTRAINT COMPLAINT_PENALTY_LINKER_FK2 FOREIGN KEY (PENALTY_ID) REFERENCES PENALTY(PENALTY_ID)
  ON DELETE CASCADE  
);

-- DROP TABLE COMPLAINT_PENALTY_LINKER;
-- DROP TABLE PENALTY;
-- DROP TABLE COMPLAINT;
-- DROP TABLE MESSAGE;
-- DROP TABLE CARD;
-- DROP TABLE WALLET;
-- DROP TABLE REVIEW;
-- DROP TABLE CUSTOMER_COUPON;
-- DROP TABLE COUPON;
-- DROP TABLE PAYMENT;
-- DROP TABLE DELIVERY;
-- DROP TABLE ORDER_;
-- DROP TABLE CART_ITEM;
-- DROP TABLE CART;
-- DROP TABLE DISH_SUB_CATEGORY;
-- DROP TABLE RIDER;
-- DROP TABLE DISH_CATEGORY_LINKER;
-- DROP TABLE DISH;
-- DROP TABLE CATEGORY;
-- DROP TABLE RESTAURANT;
-- DROP TABLE CUSTOMER;
-- DROP TABLE ADMIN;
-- DROP TABLE USERS;
-- DROP TABLE SUB_DISTRICT;
-- DROP TABLE DISTRICT;
-- DROP SEQUENCE SUB_DIST_ID_SEQ;
-- DROP SEQUENCE DISH_ID_SEQ;
-- DROP SEQUENCE SUB_CAT_ID_SEQ;
-- DROP SEQUENCE CART_ID_SEQ;
-- DROP SEQUENCE DELIVERY_ID_SEQ;
-- DROP SEQUENCE PAYMENT_ID_SEQ;
-- DROP SEQUENCE COUPON_ID_SEQ;
-- DROP SEQUENCE REVIEW_ID_SEQ;
-- DROP SEQUENCE WALLET_ID_SEQ;
-- DROP SEQUENCE MESSAGE_ID_SEQ;
-- DROP SEQUENCE COMPLAINT_ID_SEQ;
-- DROP SEQUENCE PENALTY_ID_SEQ ;